#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Translate 7 service pages from English to French."""
import os

BASE = os.path.join("c:", os.sep, "Users", "ASUS", "Desktop", "CodeSommetstudio",
                     "pikassostudio.com", "resources", "views", "pages", "services")

files = [
    "language-school-website-development.blade.php",
    "online-course-platform-development.blade.php",
    "real-estate-website-development.blade.php",
    "saas-platform-development.blade.php",
    "study-abroad-website-development.blade.php",
    "telemedicine-website-development.blade.php",
    "university-website-development.blade.php",
]

# @section line translations (key=English, value=French)
section_tr = {
    "Language School Website Development | Online Language Learning Platform - CodeSommetStudio":
        "D\u00e9veloppement de Sites Web pour \u00c9coles de Langues | Plateforme d'Apprentissage en Ligne - CodeSommetStudio",
    "Build interactive language learning platforms with AI-powered pronunciation tools, live tutoring integration, progress tracking, and engaging multimedia content. Specialized web development for language schools and institutes.":
        "Cr\u00e9ez des plateformes interactives d'apprentissage des langues avec des outils de prononciation aliment\u00e9s par l'IA, l'int\u00e9gration de tutorat en direct, le suivi des progr\u00e8s et du contenu multim\u00e9dia engageant. D\u00e9veloppement web sp\u00e9cialis\u00e9 pour les \u00e9coles de langues et instituts.",
    "language school website,language learning platform,online language courses,language institute website,ESL platform development,foreign language learning,language tutoring platform,multilingual education platform":
        "site web \u00e9cole de langues,plateforme apprentissage langues,cours de langues en ligne,site institut linguistique,d\u00e9veloppement plateforme ESL,apprentissage langues \u00e9trang\u00e8res,plateforme tutorat langues,plateforme \u00e9ducation multilingue",
    "Online Course Platform Development | Custom Course Websites | CodeSommetStudio":
        "D\u00e9veloppement de Plateformes de Cours en Ligne | Sites Web de Cours Sur Mesure | CodeSommetStudio",
    "Custom online course platform development for coaches, creators, and educators. Built 30+ course websites with video hosting, payment integration, and student engagement.":
        "D\u00e9veloppement de plateformes de cours en ligne sur mesure pour coachs, cr\u00e9ateurs et \u00e9ducateurs. Plus de 30 sites de cours cr\u00e9\u00e9s avec h\u00e9bergement vid\u00e9o, int\u00e9gration de paiement et engagement \u00e9tudiant.",
    "online course platform development,course website development,teachable alternative,kajabi alternative,custom course platform,course creator website,online learning platform":
        "d\u00e9veloppement plateforme cours en ligne,d\u00e9veloppement site de cours,alternative teachable,alternative kajabi,plateforme de cours sur mesure,site cr\u00e9ateur de cours,plateforme apprentissage en ligne",
    "Real Estate Website Development | Property Portal & Listing Platform Experts | CodeSommetStudio":
        "D\u00e9veloppement de Sites Web Immobiliers | Experts en Portails et Plateformes d'Annonces | CodeSommetStudio",
    "Custom real estate websites with advanced property search, virtual tours, agent dashboards, and lead management. Launch your property platform in 7-10 days.":
        "Sites web immobiliers sur mesure avec recherche avanc\u00e9e de biens, visites virtuelles, tableaux de bord agents et gestion de prospects. Lancez votre plateforme immobili\u00e8re en 7 \u00e0 10 jours.",
    "real estate website development,property portal development,virtual tour platform,agent dashboard,MLS integration,real estate CRM,property listing website":
        "d\u00e9veloppement site web immobilier,d\u00e9veloppement portail immobilier,plateforme visite virtuelle,tableau de bord agent,int\u00e9gration MLS,CRM immobilier,site annonces immobili\u00e8res",
    "SaaS Platform Development | B2B Software & Cloud Apps | CodeSommetStudio":
        "D\u00e9veloppement de Plateformes SaaS | Logiciels B2B & Applications Cloud | CodeSommetStudio",
    "Specialized SaaS platform development. Built 50+ B2B software platforms with user dashboards, admin panels, API integrations, and subscription billing. Contact us for pricing.":
        "D\u00e9veloppement sp\u00e9cialis\u00e9 de plateformes SaaS. Plus de 50 plateformes logicielles B2B cr\u00e9\u00e9es avec tableaux de bord utilisateurs, panneaux d'administration, int\u00e9grations API et facturation par abonnement. Contactez-nous pour les tarifs.",
    "saas platform development,b2b software development,cloud application development,saas dashboard development,subscription billing system,api integration platform,white label saas":
        "d\u00e9veloppement plateforme saas,d\u00e9veloppement logiciel b2b,d\u00e9veloppement application cloud,d\u00e9veloppement tableau de bord saas,syst\u00e8me facturation abonnement,plateforme int\u00e9gration api,saas marque blanche",
    "Study Abroad Website Development | Visa Consultancy Platforms | CodeSommetStudio":
        "D\u00e9veloppement de Sites Web \u00c9tudes \u00e0 l'\u00c9tranger | Plateformes de Conseil en Visa | CodeSommetStudio",
    "Specialized study abroad website development for overseas education consultancies. Built 40+ study abroad platforms with student portals, visa tracking, and multilingual support.":
        "D\u00e9veloppement sp\u00e9cialis\u00e9 de sites web pour \u00e9tudes \u00e0 l'\u00e9tranger pour les cabinets de conseil en \u00e9ducation internationale. Plus de 40 plateformes cr\u00e9\u00e9es avec portails \u00e9tudiants, suivi de visa et support multilingue.",
    "study abroad website development,visa consultancy website,overseas education platform,study abroad CRM,student portal development,visa tracking system,education consultancy website":
        "d\u00e9veloppement site web \u00e9tudes \u00e0 l'\u00e9tranger,site web conseil en visa,plateforme \u00e9ducation internationale,CRM \u00e9tudes \u00e0 l'\u00e9tranger,d\u00e9veloppement portail \u00e9tudiant,syst\u00e8me suivi de visa,site web conseil en \u00e9ducation",
    "Telemedicine Website Development | Virtual Care Platforms | CodeSommetStudio":
        "D\u00e9veloppement de Sites Web de T\u00e9l\u00e9m\u00e9decine | Plateformes de Soins Virtuels | CodeSommetStudio",
    "Specialized telemedicine platform development. Built 20+ virtual care platforms with video consultations, patient portals, and HIPAA compliance. Contact us for pricing.":
        "D\u00e9veloppement sp\u00e9cialis\u00e9 de plateformes de t\u00e9l\u00e9m\u00e9decine. Plus de 20 plateformes de soins virtuels cr\u00e9\u00e9es avec consultations vid\u00e9o, portails patients et conformit\u00e9 HIPAA. Contactez-nous pour les tarifs.",
    "telemedicine website development,virtual care platform,online doctor consultation,telehealth software development,video consultation platform,remote patient monitoring,health":
        "d\u00e9veloppement site web t\u00e9l\u00e9m\u00e9decine,plateforme soins virtuels,consultation m\u00e9dicale en ligne,d\u00e9veloppement logiciel t\u00e9l\u00e9sant\u00e9,plateforme consultation vid\u00e9o,surveillance patient \u00e0 distance,sant\u00e9",
    "University Website Development | Higher Education Web Design | CodeSommetStudio":
        "D\u00e9veloppement de Sites Web Universitaires | Design Web pour l'Enseignement Sup\u00e9rieur | CodeSommetStudio",
    "Custom university website development for admissions, student portals, and campus management. Built 15+ higher education websites with student enrollment systems, course catalogs, and faculty portals.":
        "D\u00e9veloppement de sites web universitaires sur mesure pour les admissions, portails \u00e9tudiants et gestion de campus. Plus de 15 sites web d'enseignement sup\u00e9rieur cr\u00e9\u00e9s avec syst\u00e8mes d'inscription, catalogues de cours et portails enseignants.",
    "university website development,higher education web design,college website development,student portal development,admissions website,campus management system,university enrollment system":
        "d\u00e9veloppement site web universitaire,design web enseignement sup\u00e9rieur,d\u00e9veloppement site web coll\u00e8ge,d\u00e9veloppement portail \u00e9tudiant,site web admissions,syst\u00e8me gestion campus,syst\u00e8me inscription universitaire",
    "CodeSommetStudio - AI-Powered Web Development Agency | Morocco":
        "CodeSommetStudio - Agence de D\u00e9veloppement Web Aliment\u00e9e par l'IA | Maroc",
    "Premium web development agency in Morocco specializing in AI-powered websites, intelligent dashboards, and SaaS platforms. Expert Next.js development for education, healthcare & business. 50+ projects delivered.":
        "Agence de d\u00e9veloppement web premium au Maroc sp\u00e9cialis\u00e9e dans les sites web aliment\u00e9s par l'IA, les tableaux de bord intelligents et les plateformes SaaS. D\u00e9veloppement Next.js expert pour l'\u00e9ducation, la sant\u00e9 et les entreprises. Plus de 50 projets livr\u00e9s.",
    "Premium web development agency specializing in AI-powered websites, intelligent dashboards, and SaaS platforms. 50+ projects delivered.":
        "Agence de d\u00e9veloppement web premium sp\u00e9cialis\u00e9e dans les sites web aliment\u00e9s par l'IA, les tableaux de bord intelligents et les plateformes SaaS. Plus de 50 projets livr\u00e9s.",
}

# Body text translations: applied as >English< -> >French<
# Sorted by length descending during application to avoid partial matches
body_tr = {
    # --- Industry names ---
    ">Industries<": ">Industries<",
    ">Now Accepting<": ">Acceptons Maintenant<",
    ">Projects<": ">Projets<",
    ">Specialized Industry<": ">Industrie Sp\u00e9cialis\u00e9e<",
    ">WE BUILD WEBSITES THAT DRIVE<": ">NOUS CR\u00c9ONS DES SITES WEB QUI G\u00c9N\u00c8RENT<",
    ">Based in<": ">Bas\u00e9 \u00e0<",
    ">7-10 Day Delivery<": ">Livraison en 7-10 Jours<",
    ">Clients<": ">Clients<",
    ">Why Choose Us<": ">Pourquoi Nous Choisir<",
    ">Why Choose CodeSommetStudio in<": ">Pourquoi Choisir CodeSommetStudio dans<",
    ">Trusted by<": ">Fait Confiance par<",
    ">Businesses<": ">Entreprises<",
    ">50+ Projects Delivered<": ">Plus de 50 Projets Livr\u00e9s<",
    ">100+ Prospects<": ">Plus de 100 Prospects<",
    ">35+ Clients<": ">Plus de 35 Clients<",
    ">Real results from<": ">R\u00e9sultats r\u00e9els de<",
    ">Common Challenges<": ">D\u00e9fis Courants<",
    ">The Challenge<": ">Le D\u00e9fi<",
    ">Businesses Face Unique Website Challenges<": ">Les Entreprises Font Face \u00e0 des D\u00e9fis Web Uniques<",
    ">businesses.<": ">entreprises.<",
    ">See Our Solution<": ">Voir Notre Solution<",
    ">Purpose-Built for<": ">Con\u00e7u Sp\u00e9cifiquement pour<",
    ">Essential Features<": ">Fonctionnalit\u00e9s Essentielles<",
    ">Websites<": ">Sites Web<",
    ">MOST POPULAR<": ">LE PLUS POPULAIRE<",
    ">AI-POWERED<": ">ALIMENT\u00c9 PAR L'IA<",
    ">Our Work in<": ">Notre Travail dans<",
    ">Success Stories from<": ">Histoires de Succ\u00e8s de<",
    ">7-10 Day Launch Timeline<": ">Calendrier de Lancement en 7-10 Jours<",
    ">Our Development Process<": ">Notre Processus de D\u00e9veloppement<",
    ">Week 1<": ">Semaine 1<",
    ">Week 2<": ">Semaine 2<",
    ">Week 3<": ">Semaine 3<",
    ">Week 4<": ">Semaine 4<",
    ">Week 1-2<": ">Semaine 1-2<",
    ">Week 2-3<": ">Semaine 2-3<",
    ">Week 3-5<": ">Semaine 3-5<",
    ">Week 5-6<": ">Semaine 5-6<",
    ">Discovery &amp; Analysis<": ">D\u00e9couverte &amp; Analyse<",
    ">Design &amp; Prototyping<": ">Design &amp; Prototypage<",
    ">Launch &amp; Support<": ">Lancement &amp; Support<",
    ">Competitor analysis report<": ">Rapport d'analyse de la concurrence<",
    ">Feature prioritization<": ">Priorisation des fonctionnalit\u00e9s<",
    ">Wireframes for key pages<": ">Maquettes fil de fer pour les pages cl\u00e9s<",
    ">High-fidelity mockups<": ">Maquettes haute fid\u00e9lit\u00e9<",
    ">Mobile-responsive design<": ">Design responsive mobile<",
    ">Frontend &amp; backend development<": ">D\u00e9veloppement frontend &amp; backend<",
    ">AI chatbot training<": ">Formation du chatbot IA<",
    ">CRM &amp; payment integration<": ">Int\u00e9gration CRM &amp; paiement<",
    ">Cross-device testing &amp; QA<": ">Tests multi-appareils &amp; QA<",
    ">Team training session<": ">Session de formation de l'\u00e9quipe<",
    ">Analytics setup<": ">Configuration des analytiques<",
    ">Ready to start your<": ">Pr\u00eat \u00e0 d\u00e9marrer votre projet<",
    ">website project?<": ">de site web ?<",
    ">Book Free Discovery Call<": ">R\u00e9server un Appel D\u00e9couverte Gratuit<",
    ">Custom Solutions, Transparent Pricing<": ">Solutions Sur Mesure, Tarification Transparente<",
    ">Book a discovery call to discuss your specific needs and get a custom quote<": ">R\u00e9servez un appel d\u00e9couverte pour discuter de vos besoins sp\u00e9cifiques et obtenir un devis personnalis\u00e9<",
    ">Recommended<": ">Recommand\u00e9<",
    ">Website Development<": ">D\u00e9veloppement de Site Web<",
    ">Complete website with AI features, dashboards, and premium design delivered in 7-10 days.<": ">Site web complet avec fonctionnalit\u00e9s IA, tableaux de bord et design premium livr\u00e9 en 7-10 jours.<",
    ">AI-powered features integration<": ">Int\u00e9gration de fonctionnalit\u00e9s aliment\u00e9es par l'IA<",
    ">Custom dashboard &amp; user portal<": ">Tableau de bord personnalis\u00e9 &amp; portail utilisateur<",
    ">Mobile-first responsive design<": ">Design responsive mobile-first<",
    ">Professional content &amp; copywriting<": ">Contenu professionnel &amp; r\u00e9daction<",
    ">Advanced SEO &amp; performance optimization<": ">SEO avanc\u00e9 &amp; optimisation des performances<",
    ">Authentication &amp; user management<": ">Authentification &amp; gestion des utilisateurs<",
    ">Payment integration ready<": ">Int\u00e9gration de paiement pr\u00eate<",
    ">Analytics &amp; conversion tracking<": ">Analytiques &amp; suivi des conversions<",
    ">Free hosting for 3 months included<": ">H\u00e9bergement gratuit pendant 3 mois inclus<",
    ">Starting from<": ">\u00c0 partir de<",
    ">Custom quote based on your project scope<": ">Devis personnalis\u00e9 selon la port\u00e9e de votre projet<",
    ">Get Custom Quote<": ">Obtenir un Devis Personnalis\u00e9<",
    ">Connect on WhatsApp<": ">Connectez sur WhatsApp<",
    ">Retainer<": ">Forfait<",
    ">Include Social Media<": ">R\u00e9seaux Sociaux Inclus<",
    ">Perfect for businesses needing ongoing AI features, dashboards, and website improvements.<": ">Parfait pour les entreprises ayant besoin de fonctionnalit\u00e9s IA continues, de tableaux de bord et d'am\u00e9liorations de site web.<",
    ">1 active project at a time<": ">1 projet actif \u00e0 la fois<",
    ">AI chatbot &amp; automation features<": ">Fonctionnalit\u00e9s chatbot IA &amp; automatisation<",
    ">Custom dashboard development<": ">D\u00e9veloppement de tableau de bord personnalis\u00e9<",
    ">48-72 hour task delivery<": ">Livraison des t\u00e2ches en 48-72 heures<",
    ">Unlimited revisions until perfect<": ">R\u00e9visions illimit\u00e9es jusqu'\u00e0 la perfection<",
    ">Full-stack development (frontend + backend)<": ">D\u00e9veloppement full-stack (frontend + backend)<",
    ">Professional SEO &amp; content strategy<": ">SEO professionnel &amp; strat\u00e9gie de contenu<",
    ">Real-time collaboration on Slack<": ">Collaboration en temps r\u00e9el sur Slack<",
    ">Premium hosting &amp; maintenance<": ">H\u00e9bergement premium &amp; maintenance<",
    ">/month<": ">/mois<",
    ">Pause or cancel anytime<": ">Pause ou annulation \u00e0 tout moment<",
    ">Book Discovery Call<": ">R\u00e9server un Appel D\u00e9couverte<",
    ">Get a comprehensive free analysis first:<": ">Obtenez d'abord une analyse gratuite compl\u00e8te :<",
    ">SEO audit<": ">Audit SEO<",
    ">Performance check<": ">V\u00e9rification des performances<",
    ">Design review<": ">Revue du design<",
    ">AI-powered recommendations<": ">Recommandations aliment\u00e9es par l'IA<",
    ">vs Others<": ">vs Autres<",
    ">See why<": ">D\u00e9couvrez pourquoi<",
    ">businesses choose CodeSommetStudio over other local agencies and international competitors.<": ">les entreprises choisissent CodeSommetStudio plut\u00f4t que d'autres agences locales et concurrents internationaux.<",
    ">Feature<": ">Fonctionnalit\u00e9<",
    ">Other<": ">Autres<",
    ">Agencies<": ">Agences<",
    ">International Agencies<": ">Agences Internationales<",
    ">Starting Price<": ">Prix de D\u00e9part<",
    ">Higher cost<": ">Co\u00fbt plus \u00e9lev\u00e9<",
    ">Much higher cost<": ">Co\u00fbt beaucoup plus \u00e9lev\u00e9<",
    ">Payment Flexibility<": ">Flexibilit\u00e9 de Paiement<",
    ">Hourly, packages, subscriptions, multi-currency<": ">Horaire, forfaits, abonnements, multi-devises<",
    ">Platform commission (10-20%)<": ">Commission de plateforme (10-20%)<",
    ">Single payment method<": ">M\u00e9thode de paiement unique<",
    ">Best Value for<": ">Meilleur Rapport Qualit\u00e9-Prix pour<",
    ">What Clients Say About Us<": ">Ce que Nos Clients Disent de Nous<",
    ">What<": ">Ce que<",
    ">Clients Say About Us<": ">les Clients Disent de Nous<",
    ">CEO at Al-Raba Technologies<": ">PDG chez Al-Raba Technologies<",
    ">Medical Director at Dubai Wellness Clinic<": ">Directrice M\u00e9dicale chez Dubai Wellness Clinic<",
    ">Dubai Healthcare City, UAE<": ">Dubai Healthcare City, EAU<",
    ">Founder at EduPath Global<": ">Fondateur chez EduPath Global<",
    ">London, UK<": ">Londres, Royaume-Uni<",
    ">Operations Director at Riad Luxe Properties<": ">Directrice des Op\u00e9rations chez Riad Luxe Properties<",
    ">Marrakech, Morocco<": ">Marrakech, Maroc<",
    ">Want to see more success stories?<": ">Vous voulez voir plus d'histoires de succ\u00e8s ?<",
    ">View all case studies<": ">Voir toutes les \u00e9tudes de cas<",
    ">Common Questions<": ">Questions Fr\u00e9quentes<",
    ">Still have questions?<": ">Vous avez encore des questions ?<",
    ">Get in touch with our<": ">Contactez notre \u00e9quipe<",
    ">team<": ">\u00e9quipe<",
    ">Global Presence<": ">Pr\u00e9sence Mondiale<",
    ">Dubai<": ">Duba\u00ef<",
    ">United States<": ">\u00c9tats-Unis<",
    ">London<": ">Londres<",
    ">United Kingdom<": ">Royaume-Uni<",
    ">Looking for<": ">Vous recherchez<",
    ">web development in a specific city?<": ">du d\u00e9veloppement web dans une ville sp\u00e9cifique ?<",
    ">View All Locations<": ">Voir Tous les Emplacements<",
    ">Contact Us for Your City<": ">Contactez-Nous pour Votre Ville<",
    ">Related Industries We Serve<": ">Industries Connexes que Nous Servons<",
    ">Explore our specialized web development services for other industries<": ">Explorez nos services de d\u00e9veloppement web sp\u00e9cialis\u00e9s pour d'autres industries<",
    ">Study Abroad Consultancy<": ">Conseil en \u00c9tudes \u00e0 l'\u00c9tranger<",
    ">Course platforms, LMS systems, and student portals for study abroad consultancies.<": ">Plateformes de cours, syst\u00e8mes LMS et portails \u00e9tudiants pour les cabinets de conseil en \u00e9tudes \u00e0 l'\u00e9tranger.<",
    ">Language Schools<": ">\u00c9coles de Langues<",
    ">Modern websites for language training institutes with course management and online learning features.<": ">Sites web modernes pour les instituts de formation linguistique avec gestion de cours et fonctionnalit\u00e9s d'apprentissage en ligne.<",
    ">Education Technology<": ">Technologie \u00c9ducative<",
    ">Online learning platforms with course management, video hosting, and student analytics.<": ">Plateformes d'apprentissage en ligne avec gestion de cours, h\u00e9bergement vid\u00e9o et analytiques \u00e9tudiants.<",
    ">Online Course Platforms<": ">Plateformes de Cours en Ligne<",
    ">Course creator platforms with content delivery, student management, and monetization features.<": ">Plateformes de cr\u00e9ation de cours avec diffusion de contenu, gestion des \u00e9tudiants et fonctionnalit\u00e9s de mon\u00e9tisation.<",
    ">Immigration Consultancy<": ">Conseil en Immigration<",
    ">Professional websites for visa and immigration consultants with case tracking and document management.<": ">Sites web professionnels pour les consultants en visa et immigration avec suivi de dossiers et gestion de documents.<",
    ">Healthcare<": ">Sant\u00e9<",
    ">Clinic websites, appointment booking systems, and patient portals compliant with health regulations.<": ">Sites web de cliniques, syst\u00e8mes de prise de rendez-vous et portails patients conformes aux r\u00e9glementations sanitaires.<",
    ">View All Industries<": ">Voir Toutes les Industries<",
    ">Explore More<": ">Explorer Plus<",
    ">Discover what makes CodeSommetStudio your ideal web development partner<": ">D\u00e9couvrez ce qui fait de CodeSommetStudio votre partenaire id\u00e9al en d\u00e9veloppement web<",
    ">Free Website Audit<": ">Audit de Site Web Gratuit<",
    ">Get AI-powered analysis with 40+ checks<": ">Obtenez une analyse aliment\u00e9e par l'IA avec plus de 40 v\u00e9rifications<",
    ">View Our Work<": ">Voir Nos R\u00e9alisations<",
    ">Explore case studies and client success stories<": ">Explorez les \u00e9tudes de cas et les histoires de succ\u00e8s de nos clients<",
    ">About CodeSommetStudio<": ">\u00c0 Propos de CodeSommetStudio<",
    ">Learn about our team and approach<": ">D\u00e9couvrez notre \u00e9quipe et notre approche<",
    ">Get in Touch<": ">Contactez-Nous<",
    ">Contact us for your project requirements<": ">Contactez-nous pour vos besoins de projet<",
    ">Back to Homepage<": ">Retour \u00e0 l'Accueil<",
    ">Explore all our services and offerings<": ">Explorez tous nos services et offres<",
    ">Ready to Build Something Extraordinary?<": ">Pr\u00eat \u00e0 Construire Quelque Chose d'Extraordinaire ?<",
    ">Join 95+ forward-thinking companies who chose excellence<": ">Rejoignez plus de 95 entreprises visionnaires qui ont choisi l'excellence<",

    # --- Case studies ---
    ">VOCATIONAL TRAINING<": ">FORMATION PROFESSIONNELLE<",
    ">EDUCATION CONSULTANCY<": ">CONSEIL EN \u00c9DUCATION<",
    ">EDUCATION SAAS<": ">SAAS \u00c9DUCATIF<",
    ">EDUCATIONAL WEBINARS<": ">WEBINAIRES \u00c9DUCATIFS<",
    ">CUSTOM COURSE WEBSITES<": ">SITES WEB DE COURS PERSONNALIS\u00c9S<",
    ">B2B TECH PLATFORM<": ">PLATEFORME TECH B2B<",
    ">STUDY ABROAD PLATFORM<": ">PLATEFORME \u00c9TUDES \u00c0 L'\u00c9TRANGER<",
    ">STUDY ABROAD<": ">\u00c9TUDES \u00c0 L'\u00c9TRANGER<",
    ">STUDENT APPLICATION PORTALS<": ">PORTAILS DE CANDIDATURE \u00c9TUDIANTE<",
    ">STUDENT ADMISSION PORTALS<": ">PORTAILS D'ADMISSION \u00c9TUDIANTE<",
    ">PROPERTY LISTINGS<": ">ANNONCES IMMOBILI\u00c8RES<",
    ">TELEMEDICINE PLATFORM<": ">PLATEFORME DE T\u00c9L\u00c9M\u00c9DECINE<",
    ">VIDEO CONSULTATIONS<": ">CONSULTATIONS VID\u00c9O<",
    ">VIRTUAL COUNSELING<": ">CONSEIL VIRTUEL<",
    ">USER DASHBOARDS<": ">TABLEAUX DE BORD UTILISATEURS<",
    ">Germany Study Abroad Consultancy Platform<": ">Plateforme de Conseil en \u00c9tudes \u00e0 l'\u00c9tranger en Allemagne<",
    ">German Vocational Training Portal<": ">Portail de Formation Professionnelle en Allemagne<",
    ">German Vocational Training Platform<": ">Plateforme de Formation Professionnelle en Allemagne<",
    ">International Education Platform<": ">Plateforme d'\u00c9ducation Internationale<",
    ">International Education Consultancy<": ">Conseil en \u00c9ducation Internationale<",
    ">+60% Applications<": ">+60% de Candidatures<",
    ">+200% Enrollments<": ">+200% d'Inscriptions<",
    ">+240% Enrollments<": ">+240% d'Inscriptions<",
    ">+150% Lead Conversion<": ">+150% de Conversion de Prospects<",
    ">+150% Webinar Attendance<": ">+150% de Participation aux Webinaires<",
    ">+250% User Growth<": ">+250% de Croissance Utilisateurs<",
    ">+300% Platform Usage<": ">+300% d'Utilisation de la Plateforme<",
    ">+45% Lead Generation<": ">+45% de G\u00e9n\u00e9ration de Prospects<",
    ">+140% Lead Growth<": ">+140% de Croissance de Prospects<",
    ">+200% Consultations<": ">+200% de Consultations<",
    ">+500% Virtual Visits<": ">+500% de Visites Virtuelles<",
    ">Germany + India<": ">Allemagne + Inde<",
    ">MS in Germany<": ">MS en Allemagne<",
    ">Enterprise platform connecting technology providers with decision makers<": ">Plateforme entreprise connectant les fournisseurs de technologie avec les d\u00e9cideurs<",
    ">AI-powered education consultancy SaaS<": ">SaaS de conseil en \u00e9ducation aliment\u00e9 par l'IA<",
    ">AI-powered virtual counseling platform<": ">Plateforme de conseil virtuel aliment\u00e9e par l'IA<",
    ">B2B technology marketplace platform<": ">Plateforme de march\u00e9 technologique B2B<",
    ">Live webinars and expert consultations<": ">Webinaires en direct et consultations d'experts<",

    # --- Industry-specific names ---
    ">Real Estate<": ">Immobilier<",
    ">SaaS &amp; B2B Software<": ">SaaS &amp; Logiciels B2B<",
    ">SaaS Platforms<": ">Plateformes SaaS<",
    ">Study Abroad &amp; Visa Consultancy<": ">\u00c9tudes \u00e0 l'\u00c9tranger &amp; Conseil en Visa<",
    ">Telemedicine &amp; Virtual Care<": ">T\u00e9l\u00e9m\u00e9decine &amp; Soins Virtuels<",
    ">Telemedicine<": ">T\u00e9l\u00e9m\u00e9decine<",
    ">Universities &amp; Higher Education<": ">Universit\u00e9s &amp; Enseignement Sup\u00e9rieur<",
    ">FinTech<": ">FinTech<",
    ">B2B SaaS<": ">SaaS B2B<",

    # --- Industry-specific feature sections ---
    ">Language Education Specialists<": ">Sp\u00e9cialistes en \u00c9ducation Linguistique<",
    ">Book Free Language Platform Demo<": ">R\u00e9server une D\u00e9mo Gratuite de Plateforme Linguistique<",
    ">View Language School Portfolio<": ">Voir le Portfolio \u00c9coles de Langues<",
    ">AI-Powered Pronunciation &amp; Feedback<": ">Prononciation &amp; Retour Aliment\u00e9s par l'IA<",
    ">Progress Tracking &amp; Certification<": ">Suivi des Progr\u00e8s &amp; Certification<",
    ">Live Tutoring &amp; Community Features<": ">Tutorat en Direct &amp; Fonctionnalit\u00e9s Communautaires<",
    ">Multimedia Learning Content<": ">Contenu d'Apprentissage Multim\u00e9dia<",
    ">Student Enrollment &amp; Retention<": ">Inscription &amp; R\u00e9tention des \u00c9tudiants<",
    ">Low Student Engagement &amp; Dropouts<": ">Faible Engagement \u00c9tudiant &amp; Abandons<",
    ">Managing Multiple Language Programs<": ">Gestion de Programmes Multilingues<",
    ">Complex Pricing &amp; Payment Models<": ">Mod\u00e8les de Tarification &amp; Paiement Complexes<",
    ">Quality Control for Online Tutors<": ">Contr\u00f4le Qualit\u00e9 des Tuteurs en Ligne<",
    ">Limited Interactive Speaking Practice<": ">Pratique Orale Interactive Limit\u00e9e<",
    ">Difficulty Measuring Language Proficiency<": ">Difficult\u00e9 \u00e0 Mesurer la Ma\u00eetrise Linguistique<",
    ">Course Enrollment &amp; Placement Test<": ">Inscription aux Cours &amp; Test de Placement<",
    ">AI Language Practice Chatbot<": ">Chatbot IA de Pratique Linguistique<",
    ">Student Learning Dashboard<": ">Tableau de Bord d'Apprentissage \u00c9tudiant<",
    ">Tutor Management &amp; Scheduling CRM<": ">CRM de Gestion &amp; Planification des Tuteurs<",
    ">Placement Test &amp; Level Assignment<": ">Test de Placement &amp; Attribution de Niveau<",
    ">Automated CEFR-aligned testing (A1-C2)<": ">Tests automatis\u00e9s align\u00e9s CECRL (A1-C2)<",
    ">Basic quiz, limited accuracy<": ">Quiz basique, pr\u00e9cision limit\u00e9e<",
    ">Manual assessment by instructors<": ">\u00c9valuation manuelle par les instructeurs<",
    ">AI Pronunciation Feedback<": ">Retour de Prononciation IA<",
    ">Speech recognition with real-time correction<": ">Reconnaissance vocale avec correction en temps r\u00e9el<",
    ">Limited to premium plans (premium plans)<": ">Limit\u00e9 aux forfaits premium (forfaits premium)<",
    ">Not available<": ">Non disponible<",
    ">Live Tutoring Integration<": ">Int\u00e9gration de Tutorat en Direct<",
    ">Built-in video + automated scheduling<": ">Vid\u00e9o int\u00e9gr\u00e9e + planification automatis\u00e9e<",
    ">Third-party fees per session<": ">Frais tiers par session<",
    ">External Zoom links, manual booking<": ">Liens Zoom externes, r\u00e9servation manuelle<",
    ">Multi-Language Program Management<": ">Gestion de Programmes Multi-Langues<",
    ">Unified dashboard for all languages<": ">Tableau de bord unifi\u00e9 pour toutes les langues<",
    ">Additional cost per language<": ">Co\u00fbt suppl\u00e9mentaire par langue<",
    ">Separate systems per language<": ">Syst\u00e8mes s\u00e9par\u00e9s par langue<",
    ">CEFR-aligned certificates with detailed analytics<": ">Certificats align\u00e9s CECRL avec analytiques d\u00e9taill\u00e9es<",
    ">Basic completion certificates only<": ">Certificats de compl\u00e9tion basiques uniquement<",
    ">Manual certificate generation<": ">G\u00e9n\u00e9ration manuelle de certificats<",
    ">Gamification &amp; Engagement<": ">Ludification &amp; Engagement<",
    ">Badges, streaks, leaderboards, challenges<": ">Badges, s\u00e9ries, classements, d\u00e9fis<",
    ">Limited gamification features<": ">Fonctionnalit\u00e9s de ludification limit\u00e9es<",
    ">Mobile Learning Experience<": ">Exp\u00e9rience d'Apprentissage Mobile<",
    ">Fully responsive + native app options<": ">Enti\u00e8rement responsive + options d'application native<",
    ">App available, but limited features<": ">Application disponible, mais fonctionnalit\u00e9s limit\u00e9es<",
    ">Desktop-only or basic mobile<": ">Bureau uniquement ou mobile basique<",

    # --- Course platform specific ---
    ">Course Platform Specialists<": ">Sp\u00e9cialistes en Plateformes de Cours<",
    ">Course Platform Experience<": ">Exp\u00e9rience en Plateformes de Cours<",
    ">Book Free Course Platform Demo<": ">R\u00e9server une D\u00e9mo Gratuite de Plateforme de Cours<",
    ">View Course Platform Portfolio<": ">Voir le Portfolio Plateformes de Cours<",
    ">Platform Fees Are Killing Your Profits<": ">Les Frais de Plateforme Tuent Vos Profits<",
    ">No Control Over Student Experience<": ">Aucun Contr\u00f4le sur l'Exp\u00e9rience \u00c9tudiant<",
    ">Limited Customization<": ">Personnalisation Limit\u00e9e<",
    ">Platform Lock-In Risk<": ">Risque de Verrouillage de Plateforme<",
    ">Poor SEO &amp; Discoverability<": ">Mauvais SEO &amp; D\u00e9couvrabilit\u00e9<",
    ">No Analytics on User Behavior<": ">Aucune Analytique sur le Comportement Utilisateur<",
    ">Video Course Player<": ">Lecteur Vid\u00e9o de Cours<",
    ">Student Progress Tracking<": ">Suivi des Progr\u00e8s \u00c9tudiants<",
    ">Membership &amp; Access Control<": ">Adh\u00e9sion &amp; Contr\u00f4le d'Acc\u00e8s<",
    ">Community &amp; Discussion<": ">Communaut\u00e9 &amp; Discussion<",
    ">Instructor &amp; Creator Tools<": ">Outils Instructeur &amp; Cr\u00e9ateur<",
    ">Video Hosting<": ">H\u00e9bergement Vid\u00e9o<",
    ">Student Data Ownership<": ">Propri\u00e9t\u00e9 des Donn\u00e9es \u00c9tudiantes<",
    ">Course/Student Limits<": ">Limites Cours/\u00c9tudiants<",
    ">Custom Branding<": ">Marque Personnalis\u00e9e<",
    ">Platform Transaction Fees<": ">Frais de Transaction de Plateforme<",
    ">Video Streaming Optimized<": ">Streaming Vid\u00e9o Optimis\u00e9<",
    ">Completion Rate Optimization<": ">Optimisation du Taux de Compl\u00e9tion<",
    ">Monetization-First Design<": ">Design Ax\u00e9 sur la Mon\u00e9tisation<",
    ">Course Structure &amp; Design<": ">Structure &amp; Design de Cours<",
    ">Development &amp; Video Integration<": ">D\u00e9veloppement &amp; Int\u00e9gration Vid\u00e9o<",
    ">Payment &amp; Content Migration<": ">Paiement &amp; Migration de Contenu<",
    ">Testing &amp; Launch<": ">Tests &amp; Lancement<",
    ">Course content audit<": ">Audit du contenu de cours<",
    ">Course content migration<": ">Migration du contenu de cours<",
    ">Student data migration<": ">Migration des donn\u00e9es \u00e9tudiantes<",
    ">Video hosting setup<": ">Configuration de l'h\u00e9bergement vid\u00e9o<",
    ">Video player integration<": ">Int\u00e9gration du lecteur vid\u00e9o<",
    ">Stripe &amp; analytics integration<": ">Int\u00e9gration Stripe &amp; analytiques<",
    ">Payment gateway setup<": ">Configuration de la passerelle de paiement<",
    ">Cross-browser and mobile responsiveness testing<": ">Tests de compatibilit\u00e9 navigateur et responsive mobile<",
    ">Launch marketing materials<": ">Mat\u00e9riel marketing de lancement<",
    ">Course Platform Development<": ">D\u00e9veloppement de Plateforme de Cours<",
    ">Course Catalog System<": ">Syst\u00e8me de Catalogue de Cours<",
    ">30+ course websites<": ">Plus de 30 sites web de cours<",
    ">Annual Platform Fees<": ">Frais Annuels de Plateforme<",
    ">Teachable hosting<": ">H\u00e9bergement Teachable<",
    ">Kajabi hosting<": ">H\u00e9bergement Kajabi<",

    # --- Real Estate specific ---
    ">Advanced Property Search<": ">Recherche Avanc\u00e9e de Biens<",
    ">360\u00b0 Virtual Tour Platform<": ">Plateforme de Visite Virtuelle 360\u00b0<",
    ">360\u00b0 Virtual Tours<": ">Visites Virtuelles 360\u00b0<",
    ">Agent Dashboard &amp; CRM<": ">Tableau de Bord Agent &amp; CRM<",
    ">Agent Dashboard<": ">Tableau de Bord Agent<",
    ">Agent Dashboards<": ">Tableaux de Bord Agents<",
    ">Market Analytics Dashboard<": ">Tableau de Bord Analytique du March\u00e9<",
    ">Market Analytics<": ">Analytique du March\u00e9<",
    ">MLS Integration<": ">Int\u00e9gration MLS<",
    ">Lead Management CRM<": ">CRM de Gestion de Prospects<",
    ">Lead Management<": ">Gestion de Prospects<",
    ">Virtual Tours<": ">Visites Virtuelles<",
    ">Multi-Filter Search<": ">Recherche Multi-Filtres<",
    ">Buyers Can&#x27;t Find Properties<": ">Les Acheteurs ne Trouvent pas les Biens<",
    ">Property Viewing Challenges<": ">D\u00e9fis de Visite de Biens<",
    ">Prospects Fall Through Cracks<": ">Les Prospects Passent entre les Mailles<",
    ">Agents Lack Management Tools<": ">Les Agents Manquent d'Outils de Gestion<",
    ">No Market Insights<": ">Aucune Analyse du March\u00e9<",
    ">Outdated Listing Information<": ">Informations d'Annonces Obsol\u00e8tes<",
    ">Agent Tools &amp; Lead Management<": ">Outils Agents &amp; Gestion de Prospects<",
    ">Discovery &amp; Property Portal Design<": ">D\u00e9couverte &amp; Design du Portail Immobilier<",
    ">real estate<": ">immobilier<",

    # --- SaaS specific ---
    ">SaaS Experience<": ">Exp\u00e9rience SaaS<",
    ">Growth-Focused SaaS Design<": ">Design SaaS Ax\u00e9 sur la Croissance<",
    ">AI-Powered SaaS Features<": ">Fonctionnalit\u00e9s SaaS Aliment\u00e9es par l'IA<",
    ">User Dashboard<": ">Tableau de Bord Utilisateur<",
    ">Admin Panel<": ">Panneau d'Administration<",
    ">Subscription Billing<": ">Facturation par Abonnement<",
    ">API Integration Hub<": ">Hub d'Int\u00e9gration API<",
    ">Multi-Tenant Architecture<": ">Architecture Multi-Tenant<",
    ">High User Churn in First Week<": ">Taux d'Attrition \u00c9lev\u00e9 la Premi\u00e8re Semaine<",
    ">Can&#x27;t Integrate Your Tools<": ">Impossible d'Int\u00e9grer Vos Outils<",
    ">MVP Doesn&#x27;t Scale to Production<": ">Le MVP ne Passe pas \u00e0 l'\u00c9chelle en Production<",
    ">Manual Billing and Invoicing<": ">Facturation et Factures Manuelles<",
    ">Integration Chaos<": ">Chaos d'Int\u00e9gration<",
    ">Disconnected Systems<": ">Syst\u00e8mes D\u00e9connect\u00e9s<",
    ">Discovery &amp; Architecture<": ">D\u00e9couverte &amp; Architecture<",
    ">Core Platform Development<": ">D\u00e9veloppement de la Plateforme Principale<",
    ">Testing, Analytics &amp; Launch<": ">Tests, Analytiques &amp; Lancement<",
    ">saas &amp; b2b software<": ">SaaS &amp; logiciels B2B<",
    ">View SaaS Portfolio<": ">Voir le Portfolio SaaS<",
    ">50+ SaaS projects<": ">Plus de 50 projets SaaS<",
    ">Fast MVP to Market<": ">MVP Rapide vers le March\u00e9<",
    ">Dashboard &amp; Admin Panel<": ">Tableau de Bord &amp; Panneau d'Administration<",
    ">API Development<": ">D\u00e9veloppement API<",
    ">Billing Integration<": ">Int\u00e9gration de Facturation<",
    ">Scalability Support<": ">Support de Scalabilit\u00e9<",
    ">60% of Our Clients Are in SaaS<": ">60% de Nos Clients sont dans le SaaS<",
    ">Outdated API Documentation<": ">Documentation API Obsol\u00e8te<",
    ">AI Analytics<": ">Analytiques IA<",

    # --- Study abroad specific ---
    ">Study Abroad Experience<": ">Exp\u00e9rience \u00c9tudes \u00e0 l'\u00c9tranger<",
    ">Lead Generation Experts for Study Abroad<": ">Experts en G\u00e9n\u00e9ration de Prospects pour \u00c9tudes \u00e0 l'\u00c9tranger<",
    ">AI-Powered Student Counseling<": ">Conseil \u00c9tudiant Aliment\u00e9 par l'IA<",
    ">Application Portal<": ">Portail de Candidature<",
    ">Application Portal Design<": ">Design du Portail de Candidature<",
    ">Student Dashboard<": ">Tableau de Bord \u00c9tudiant<",
    ">Multilingual &amp; Multi-Currency<": ">Multilingue &amp; Multi-Devises<",
    ">Multilingual Support<": ">Support Multilingue<",
    ">AI Chatbot for Student Queries<": ">Chatbot IA pour les Questions \u00c9tudiantes<",
    ">AI Chatbot<": ">Chatbot IA<",
    ">CRM Integration<": ">Int\u00e9gration CRM<",
    ">International Student Support<": ">Support aux \u00c9tudiants Internationaux<",
    ">International Student Ready<": ">Pr\u00eat pour les \u00c9tudiants Internationaux<",
    ">Poor SEO Rankings - Losing Students to Competitors<": ">Mauvais Classement SEO - Perte d'\u00c9tudiants au Profit des Concurrents<",
    ">No Lead Qualification - Time Wasted on Unqualified Students<": ">Aucune Qualification de Prospects - Temps Perdu sur des \u00c9tudiants Non Qualifi\u00e9s<",
    ">Manual Document Management Chaos<": ">Chaos de Gestion Manuelle des Documents<",
    ">Chaotic Student Communication Across Channels<": ">Communication \u00c9tudiante Chaotique \u00e0 Travers les Canaux<",
    ">Multilingual Support is Expensive and Inconsistent<": ">Le Support Multilingue est Co\u00fbteux et Incoh\u00e9rent<",
    ">Low Application Conversion Rates<": ">Faibles Taux de Conversion des Candidatures<",
    ">Discovery &amp; Market Analysis<": ">D\u00e9couverte &amp; Analyse du March\u00e9<",
    ">Visa Workflow Development<": ">D\u00e9veloppement du Flux de Travail Visa<",
    ">Launch &amp; Transition<": ">Lancement &amp; Transition<",
    ">study abroad &amp; visa consultancy<": ">\u00e9tudes \u00e0 l'\u00e9tranger &amp; conseil en visa<",
    ">40+ study abroad projects<": ">Plus de 40 projets \u00e9tudes \u00e0 l'\u00e9tranger<",
    ">View Study Abroad Portfolio<": ">Voir le Portfolio \u00c9tudes \u00e0 l'\u00c9tranger<",
    ">60% of Our Clients Are Study Abroad Consultancies<": ">60% de Nos Clients sont des Cabinets de Conseil en \u00c9tudes \u00e0 l'\u00c9tranger<",
    ">Generic Website Builders Don&#x27;t Work for Study Abroad<": ">Les Constructeurs de Sites G\u00e9n\u00e9riques ne Fonctionnent pas pour les \u00c9tudes \u00e0 l'\u00c9tranger<",

    # --- Telemedicine specific ---
    ">Telemedicine Experience<": ">Exp\u00e9rience en T\u00e9l\u00e9m\u00e9decine<",
    ">Video Consultation Platform<": ">Plateforme de Consultation Vid\u00e9o<",
    ">Patient Portal<": ">Portail Patient<",
    ">HIPAA Compliance<": ">Conformit\u00e9 HIPAA<",
    ">HIPAA Compliant by Default<": ">Conforme HIPAA par D\u00e9faut<",
    ">AI Symptom Checker<": ">V\u00e9rificateur de Sympt\u00f4mes IA<",
    ">AI-Powered Health Features<": ">Fonctionnalit\u00e9s Sant\u00e9 Aliment\u00e9es par l'IA<",
    ">EMR Integration<": ">Int\u00e9gration DME<",
    ">Healthcare Compliance Support<": ">Support de Conformit\u00e9 Sant\u00e9<",
    ">Complete Patient Journey<": ">Parcours Patient Complet<",
    ">Chaotic Patient Communication<": ">Communication Patient Chaotique<",
    ">Doctors Waste Time on No-Shows<": ">Les M\u00e9decins Perdent du Temps avec les Absences<",
    ">Poor Patient Record Management<": ">Mauvaise Gestion des Dossiers Patients<",
    ">Manual Payment &amp; Insurance Processing<": ">Traitement Manuel des Paiements &amp; Assurances<",
    ">Low Patient Retention &amp; Engagement<": ">Faible R\u00e9tention &amp; Engagement des Patients<",
    ">Generic Platforms Aren&#x27;t HIPAA Compliant<": ">Les Plateformes G\u00e9n\u00e9riques ne sont pas Conformes HIPAA<",
    ">Discovery &amp; Telemedicine Strategy<": ">D\u00e9couverte &amp; Strat\u00e9gie de T\u00e9l\u00e9m\u00e9decine<",
    ">Design &amp; Patient Experience<": ">Design &amp; Exp\u00e9rience Patient<",
    ">Development &amp; Integration<": ">D\u00e9veloppement &amp; Int\u00e9gration<",
    ">Testing, Compliance &amp; Launch<": ">Tests, Conformit\u00e9 &amp; Lancement<",
    ">telemedicine &amp; virtual care<": ">t\u00e9l\u00e9m\u00e9decine &amp; soins virtuels<",
    ">View Healthcare Portfolio<": ">Voir le Portfolio Sant\u00e9<",
    ">20+ telehealth platforms built<": ">Plus de 20 plateformes de t\u00e9l\u00e9sant\u00e9 cr\u00e9\u00e9es<",
    ">50% of Our Clients Are Telemedicine Providers<": ">50% de Nos Clients sont des Prestataires de T\u00e9l\u00e9m\u00e9decine<",
    ">Fast Deployment for Healthcare<": ">D\u00e9ploiement Rapide pour la Sant\u00e9<",
    ">Book Free Telemedicine Demo<": ">R\u00e9server une D\u00e9mo T\u00e9l\u00e9m\u00e9decine Gratuite<",
    ">Appointment &amp; Analytics Dashboard<": ">Tableau de Bord de Rendez-vous &amp; Analytiques<",

    # --- University specific ---
    ">Higher Education Experience<": ">Exp\u00e9rience en Enseignement Sup\u00e9rieur<",
    ">Higher Education Web Experts<": ">Experts Web en Enseignement Sup\u00e9rieur<",
    ">Student Admissions Portal<": ">Portail d'Admissions \u00c9tudiantes<",
    ">Course Catalog &amp; Registration<": ">Catalogue de Cours &amp; Inscription<",
    ">Faculty &amp; Staff Portal<": ">Portail Enseignants &amp; Personnel<",
    ">LMS Integration<": ">Int\u00e9gration LMS<",
    ">FERPA Compliance<": ">Conformit\u00e9 FERPA<",
    ">Admissions-Focused Design<": ">Design Ax\u00e9 sur les Admissions<",
    ">Integrated Student Systems<": ">Syst\u00e8mes \u00c9tudiants Int\u00e9gr\u00e9s<",
    ">Fast Deployment for Admission Seasons<": ">D\u00e9ploiement Rapide pour les Saisons d'Admission<",
    ">Compliance &amp; Accessibility<": ">Conformit\u00e9 &amp; Accessibilit\u00e9<",
    ">Outdated University Websites<": ">Sites Web Universitaires Obsol\u00e8tes<",
    ">Manual Paper-Based Admissions<": ">Admissions Manuelles sur Papier<",
    ">No Student Self-Service Portal<": ">Aucun Portail en Libre-Service \u00c9tudiant<",
    ">Poor International Student Experience<": ">Mauvaise Exp\u00e9rience pour les \u00c9tudiants Internationaux<",
    ">Discovery &amp; Planning<": ">D\u00e9couverte &amp; Planification<",
    ">universities &amp; higher education<": ">universit\u00e9s &amp; enseignement sup\u00e9rieur<",
    ">15+ university websites<": ">Plus de 15 sites web universitaires<",
    ">View University Portfolio<": ">Voir le Portfolio Universitaire<",
    ">Book Free University Website Demo<": ">R\u00e9server une D\u00e9mo Gratuite de Site Web Universitaire<",

    # --- Comparison table items ---
    ">Turnaround Time<": ">D\u00e9lai de R\u00e9alisation<",
    ">7-10 days<": ">7-10 jours<",
    ">7-10 days (MVP)<": ">7-10 jours (MVP)<",
    ">10-14 days<": ">10-14 jours<",
    ">3-4 weeks<": ">3-4 semaines<",
    ">4-6 weeks<": ">4-6 semaines<",
    ">6-8 weeks<": ">6-8 semaines<",
    ">8-12 weeks<": ">8-12 semaines<",
    ">12+ weeks<": ">Plus de 12 semaines<",
    ">12-16 weeks<": ">12-16 semaines<",
    ">3-6 months with multiple revision rounds<": ">3-6 mois avec plusieurs cycles de r\u00e9vision<",
    ">6-12 months with hiring, training, and development<": ">6-12 mois avec recrutement, formation et d\u00e9veloppement<",
    ">Built-in<": ">Int\u00e9gr\u00e9<",
    ">Custom-built<": ">Construit sur mesure<",
    ">Limited<": ">Limit\u00e9<",
    ">Not included<": ">Non inclus<",
    ">Not certified<": ">Non certifi\u00e9<",
    ">Extra cost<": ">Co\u00fbt suppl\u00e9mentaire<",
    ">Extra fees<": ">Frais suppl\u00e9mentaires<",
    ">Extra compliance cost<": ">Co\u00fbt de conformit\u00e9 suppl\u00e9mentaire<",
    ">Templates only<": ">Mod\u00e8les uniquement<",
    ">Full customization<": ">Personnalisation compl\u00e8te<",
    ">No priority<": ">Aucune priorit\u00e9<",
    ">Priority support<": ">Support prioritaire<",
    ">Priority HIPAA support<": ">Support HIPAA prioritaire<",
    ">Basic<": ">Basique<",
    ">Unlimited<": ">Illimit\u00e9<",
    ">Limited by plan<": ">Limit\u00e9 par forfait<",
    ">100% yours<": ">100% le v\u00f4tre<",
    ">0% (you own it)<": ">0% (c'est le v\u00f4tre)<",
    ">Platform owns it<": ">La plateforme en est propri\u00e9taire<",
    ">Generic experience<": ">Exp\u00e9rience g\u00e9n\u00e9rique<",
    ">Generic web development<": ">D\u00e9veloppement web g\u00e9n\u00e9raliste<",
    ">Generic dashboards<": ">Tableaux de bord g\u00e9n\u00e9riques<",
    ">Generic chatbot<": ">Chatbot g\u00e9n\u00e9rique<",
    ">English only<": ">Anglais uniquement<",
    ">Static pages<": ">Pages statiques<",
    ">REST only<": ">REST uniquement<",
    ">Full REST + GraphQL<": ">REST complet + GraphQL<",
    ">Standard queue<": ">File d'attente standard<",
    ">Stripe only<": ">Stripe uniquement<",
    ">Basic forms only<": ">Formulaires basiques uniquement<",
    ">Basic forms<": ">Formulaires basiques<",
    ">Basic templates only<": ">Mod\u00e8les basiques uniquement<",
    ">Basic listing management, no CRM<": ">Gestion basique des annonces, pas de CRM<",
    ">Basic keyword search only<": ">Recherche par mots-cl\u00e9s basique uniquement<",
    ">Basic contact forms, no automation<": ">Formulaires de contact basiques, pas d'automatisation<",
    ">Basic Zoom embed<": ">Int\u00e9gration Zoom basique<",
    ">Static image galleries only<": ">Galeries d'images statiques uniquement<",
    ">Limited filters, no map integration<": ">Filtres limit\u00e9s, pas d'int\u00e9gration de carte<",
    ">Manual email follow-ups, high risk of lead loss<": ">Suivis par e-mail manuels, risque \u00e9lev\u00e9 de perte de prospects<",
    ">Manual CSV imports or no integration<": ">Importations CSV manuelles ou pas d'int\u00e9gration<",
    ">Manual spreadsheets or expensive third-party tools<": ">Tableurs manuels ou outils tiers co\u00fbteux<",
    ">Third-party only<": ">Tiers uniquement<",
    ">Third-party embed with limited customization<": ">Int\u00e9gration tierce avec personnalisation limit\u00e9e<",
    ">Separate mobile app required for good UX<": ">Application mobile s\u00e9par\u00e9e requise pour une bonne UX<",
    ">Desktop-first design, clunky mobile<": ">Design bureau d'abord, mobile peu ergonomique<",
    ">Requires complex API setup and maintenance<": ">N\u00e9cessite une configuration API complexe et maintenance<",
    ">No healthcare experience<": ">Aucune exp\u00e9rience en sant\u00e9<",
    ">Fully responsive with native-like mobile experience<": ">Enti\u00e8rement responsive avec exp\u00e9rience mobile similaire au natif<",
    ">Mobile Experience<": ">Exp\u00e9rience Mobile<",
    ">7-10 days for MVP, 2-3 weeks for full platform<": ">7-10 jours pour le MVP, 2-3 semaines pour la plateforme compl\u00e8te<",
    ">Built-in with BAA signing<": ">Int\u00e9gr\u00e9 avec signature BAA<",
    ">Trained on visa requirements<": ">Form\u00e9 sur les exigences de visa<",
    ">Trained on your metrics<": ">Form\u00e9 sur vos m\u00e9triques<",
    ">Trained on medical data<": ">Form\u00e9 sur des donn\u00e9es m\u00e9dicales<",

    # --- Feature details ---
    ">Multi-step forms with validation<": ">Formulaires multi-\u00e9tapes avec validation<",
    ">Secure document upload (PDF, JPG, PNG)<": ">T\u00e9l\u00e9chargement s\u00e9curis\u00e9 de documents (PDF, JPG, PNG)<",
    ">Real-time status tracking<": ">Suivi de statut en temps r\u00e9el<",
    ">Auto email/SMS notifications<": ">Notifications automatiques par e-mail/SMS<",
    ">50+ languages supported<": ">Plus de 50 langues support\u00e9es<",
    ">50+ languages included<": ">Plus de 50 langues incluses<",
    ">50+ languages (Hindi, Arabic, Urdu, Chinese)<": ">Plus de 50 langues (hindi, arabe, ourdou, chinois)<",
    ">Course recommendations<": ">Recommandations de cours<",
    ">Eligibility checker<": ">V\u00e9rificateur d'\u00e9ligibilit\u00e9<",
    ">Auto CRM sync<": ">Synchronisation CRM automatique<",
    ">Auto CRM sync for qualified leads<": ">Synchronisation CRM automatique pour les prospects qualifi\u00e9s<",
    ">Visual progress timeline<": ">Chronologie visuelle des progr\u00e8s<",
    ">Document management<": ">Gestion des documents<",
    ">Payment receipts<": ">Re\u00e7us de paiement<",
    ">Direct messaging<": ">Messagerie directe<",
    ">Auto lead scoring<": ">Notation automatique des prospects<",
    ">Follow-up reminders<": ">Rappels de suivi<",
    ">Drag-and-drop pipeline<": ">Pipeline glisser-d\u00e9poser<",
    ">Revenue forecasting<": ">Pr\u00e9vision de revenus<",
    ">Direct messaging with counselor<": ">Messagerie directe avec le conseiller<",
    ">Application status tracking<": ">Suivi du statut de candidature<",
    ">Payment tracking and receipts<": ">Suivi des paiements et re\u00e7us<",
    ">Document upload &amp; verification<": ">T\u00e9l\u00e9chargement &amp; v\u00e9rification de documents<",
    ">Multi-step application forms<": ">Formulaires de candidature multi-\u00e9tapes<",
    ">Email notifications<": ">Notifications par e-mail<",
    ">Automated email notifications<": ">Notifications par e-mail automatis\u00e9es<",
    ">Automated email notifications for inquiries<": ">Notifications par e-mail automatis\u00e9es pour les demandes<",
    ">Country-specific visa requirements<": ">Exigences de visa sp\u00e9cifiques au pays<",
    ">University eligibility checker<": ">V\u00e9rificateur d'\u00e9ligibilit\u00e9 universitaire<",
    ">Multi-step forms with country selection<": ">Formulaires multi-\u00e9tapes avec s\u00e9lection du pays<",
    ">Document upload (Passport, Transcripts, Test Scores)<": ">T\u00e9l\u00e9chargement de documents (Passeport, Relev\u00e9s de Notes, Scores de Tests)<",
    ">Auto email/SMS notifications at each stage<": ">Notifications automatiques par e-mail/SMS \u00e0 chaque \u00e9tape<",
    ">Document checklist with upload status<": ">Liste de v\u00e9rification des documents avec statut de t\u00e9l\u00e9chargement<",
    ">Real-time application status tracking<": ">Suivi du statut de candidature en temps r\u00e9el<",
    ">Auto lead scoring (Budget + Grades + Test Scores)<": ">Notation automatique des prospects (Budget + Notes + Scores de Tests)<",
    ">Follow-up reminders for counselors<": ">Rappels de suivi pour les conseillers<",
    ">Revenue forecasting per intake<": ">Pr\u00e9vision de revenus par rentr\u00e9e<",

    # --- Dashboard features ---
    ">Customizable widgets &amp; layouts<": ">Widgets &amp; mises en page personnalisables<",
    ">Real-time usage analytics<": ">Analytiques d'utilisation en temps r\u00e9el<",
    ">Activity timeline &amp; notifications<": ">Chronologie d'activit\u00e9 &amp; notifications<",
    ">Export reports (CSV, PDF)<": ">Export de rapports (CSV, PDF)<",
    ">Role-based access control (RBAC)<": ">Contr\u00f4le d'acc\u00e8s bas\u00e9 sur les r\u00f4les (RBAC)<",
    ">User activity monitoring<": ">Surveillance de l'activit\u00e9 utilisateur<",
    ">System health dashboard<": ">Tableau de bord de sant\u00e9 syst\u00e8me<",
    ">Bulk operations &amp; automation<": ">Op\u00e9rations en masse &amp; automatisation<",
    ">Multiple pricing tiers<": ">Plusieurs niveaux de tarification<",
    ">Usage-based billing<": ">Facturation bas\u00e9e sur l'utilisation<",
    ">Failed payment recovery<": ">R\u00e9cup\u00e9ration des paiements \u00e9chou\u00e9s<",
    ">Automatic invoice generation<": ">G\u00e9n\u00e9ration automatique de factures<",
    ">OAuth 2.0 &amp; API keys<": ">OAuth 2.0 &amp; cl\u00e9s API<",
    ">Interactive API playground<": ">Terrain de jeu API interactif<",
    ">Webhook event management<": ">Gestion des \u00e9v\u00e9nements webhook<",
    ">API development &amp; documentation<": ">D\u00e9veloppement &amp; documentation API<",
    ">Real-time logs &amp; debugging<": ">Journaux en temps r\u00e9el &amp; d\u00e9bogage<",

    # --- Telemedicine features ---
    ">End-to-end encrypted video (WebRTC)<": ">Vid\u00e9o chiffr\u00e9e de bout en bout (WebRTC)<",
    ">Screen sharing for reviewing reports<": ">Partage d'\u00e9cran pour la revue de rapports<",
    ">Real-time chat during calls<": ">Chat en temps r\u00e9el pendant les appels<",
    ">HD video with recording<": ">Vid\u00e9o HD avec enregistrement<",
    ">Picture-in-picture mode<": ">Mode image dans l'image<",
    ">Automatic consultation recording &amp; notes<": ">Enregistrement automatique de consultation &amp; notes<",
    ">View consultation history &amp; prescriptions<": ">Voir l'historique des consultations &amp; prescriptions<",
    ">Upload medical reports &amp; lab results<": ">T\u00e9l\u00e9charger les rapports m\u00e9dicaux &amp; r\u00e9sultats de laboratoire<",
    ">Secure messaging with doctors<": ">Messagerie s\u00e9curis\u00e9e avec les m\u00e9decins<",
    ">Payment history &amp; insurance claims<": ">Historique de paiement &amp; r\u00e9clamations d'assurance<",
    ">Patient medical history access<": ">Acc\u00e8s \u00e0 l'historique m\u00e9dical du patient<",
    ">Conversational symptom assessment<": ">\u00c9valuation conversationnelle des sympt\u00f4mes<",
    ">Specialist recommendation engine<": ">Moteur de recommandation de sp\u00e9cialistes<",
    ">Urgency level classification<": ">Classification du niveau d'urgence<",
    ">Calendar sync (Google/Outlook)<": ">Synchronisation de calendrier (Google/Outlook)<",
    ">Automated appointment booking<": ">Prise de rendez-vous automatis\u00e9e<",
    ">Revenue &amp; consultation analytics<": ">Analytiques de revenus &amp; consultations<",
    ">Provider dashboard for managing virtual appointments<": ">Tableau de bord prestataire pour la gestion des rendez-vous virtuels<",
    ">End-to-end encrypted video consultation system<": ">Syst\u00e8me de consultation vid\u00e9o chiffr\u00e9 de bout en bout<",
    ">E-prescribing integration with pharmacy networks<": ">Int\u00e9gration d'e-prescription avec les r\u00e9seaux de pharmacies<",
    ">Prescription management system<": ">Syst\u00e8me de gestion des prescriptions<",
    ">Digital stethoscope and remote monitoring device integration<": ">Int\u00e9gration de st\u00e9thoscope num\u00e9rique et dispositifs de surveillance \u00e0 distance<",

    # --- University features ---
    ">Stakeholder interviews (admissions, IT, faculty)<": ">Entretiens avec les parties prenantes (admissions, IT, enseignants)<",
    ">Admissions portal system<": ">Syst\u00e8me de portail d'admissions<",
    ">Course catalog &amp; enrollment<": ">Catalogue de cours &amp; inscription<",
    ">Online course registration<": ">Inscription aux cours en ligne<",
    ">Student dashboard<": ">Tableau de bord \u00e9tudiant<",
    ">Attendance management<": ">Gestion de la pr\u00e9sence<",
    ">Grade submission<": ">Soumission des notes<",
    ">Course material uploads<": ">T\u00e9l\u00e9chargement de supports de cours<",
    ">Student messaging<": ">Messagerie \u00e9tudiante<",
    ">Academic records access<": ">Acc\u00e8s aux dossiers acad\u00e9miques<",
    ">Fee payment &amp; receipts<": ">Paiement des frais &amp; re\u00e7us<",
    ">Class schedules<": ">Emplois du temps des cours<",
    ">Grade reports<": ">Relev\u00e9s de notes<",
    ">Security audit &amp; penetration testing<": ">Audit de s\u00e9curit\u00e9 &amp; tests de p\u00e9n\u00e9tration<",
    ">Data migration<": ">Migration des donn\u00e9es<",
    ">Staff training sessions<": ">Sessions de formation du personnel<",
    ">Searchable course database<": ">Base de donn\u00e9es de cours consultable<",
    ">Searchable with registration<": ">Consultable avec inscription<",
    ">Real-time seat availability<": ">Disponibilit\u00e9 des places en temps r\u00e9el<",
    ">Prerequisite checking<": ">V\u00e9rification des pr\u00e9requis<",

    # --- Video/course features ---
    ">Brand integration<": ">Int\u00e9gration de la marque<",
    ">Keyboard shortcuts<": ">Raccourcis clavier<",
    ">Watch history &amp; bookmarks<": ">Historique de visionnage &amp; signets<",
    ">Adaptive streaming quality<": ">Qualit\u00e9 de streaming adaptative<",
    ">Lesson completion tracking<": ">Suivi de compl\u00e9tion des le\u00e7ons<",
    ">Automated certificates<": ">Certificats automatis\u00e9s<",
    ">Quiz scores &amp; assessments<": ">Scores de quiz &amp; \u00e9valuations<",
    ">Student engagement metrics<": ">M\u00e9triques d'engagement \u00e9tudiant<",
    ">One-time &amp; subscription pricing<": ">Tarification unique &amp; par abonnement<",
    ">Course bundles &amp; upsells<": ">Packs de cours &amp; ventes additionnelles<",
    ">Lifetime access options<": ">Options d'acc\u00e8s \u00e0 vie<",
    ">Drip content scheduling<": ">Planification de contenu progressif<",
    ">Q&amp;A discussion boards<": ">Forums de discussion Q&amp;R<",
    ">Private messaging<": ">Messagerie priv\u00e9e<",
    ">Lesson-level comments<": ">Commentaires au niveau des le\u00e7ons<",
    ">Multilingual + multi-currency<": ">Multilingue + multi-devises<",

    # --- Real estate features ---
    ">Advanced filters: amenities, school districts, HOA fees, lot size<": ">Filtres avanc\u00e9s : \u00e9quipements, districts scolaires, frais HOA, taille du terrain<",
    ">Interactive map view with property clustering and neighborhood boundaries<": ">Vue carte interactive avec regroupement de biens et limites de quartier<",
    ">Interactive floor plans with room measurements<": ">Plans interactifs avec mesures des pi\u00e8ces<",
    ">VR headset support for immersive viewing experience<": ">Support de casque VR pour une exp\u00e9rience de visualisation immersive<",
    ">HD video walkthroughs and drone aerial footage<": ">Visites vid\u00e9o HD et images a\u00e9riennes par drone<",
    ">Comparable property analysis (CMA) tool<": ">Outil d'analyse comparative de biens (ACM)<",
    ">Investment ROI calculators and rental yield estimators<": ">Calculateurs de ROI d'investissement et estimateurs de rendement locatif<",
    ">Real-time pricing trends and market heat maps<": ">Tendances de prix en temps r\u00e9el et cartes thermiques du march\u00e9<",
    ">Neighborhood insights: schools, crime, transit, amenities<": ">Informations sur le quartier : \u00e9coles, criminalit\u00e9, transports, \u00e9quipements<",
    ">Real-time MLS data sync with automatic updates<": ">Synchronisation MLS en temps r\u00e9el avec mises \u00e0 jour automatiques<",
    ">Automated capture, follow-up workflows, email campaigns<": ">Capture automatis\u00e9e, workflows de suivi, campagnes e-mail<",
    ">Full listing CRUD with photo uploads and virtual tour integration<": ">CRUD complet des annonces avec t\u00e9l\u00e9chargement de photos et int\u00e9gration de visites virtuelles<",
    ">Performance analytics: views, inquiries, conversion rates<": ">Analytiques de performance : vues, demandes, taux de conversion<",
    ">Showing scheduler with calendar integration and SMS reminders<": ">Planificateur de visites avec int\u00e9gration de calendrier et rappels SMS<",
    ">Full CRM with lead tracking, scheduling, analytics<": ">CRM complet avec suivi des prospects, planification, analytiques<",
    ">Agent dashboard with listing CRUD operations<": ">Tableau de bord agent avec op\u00e9rations CRUD d'annonces<",
    ">Saved searches with instant email alerts for new listings<": ">Recherches sauvegard\u00e9es avec alertes e-mail instantan\u00e9es pour les nouvelles annonces<",
    ">Target market analysis and buyer persona research<": ">Analyse du march\u00e9 cible et recherche de personas acheteurs<",
    ">User persona &amp; journey mapping<": ">Cartographie des personas utilisateurs &amp; parcours<",
    ">Property database schema and API endpoints<": ">Sch\u00e9ma de base de donn\u00e9es immobili\u00e8re et points d'acc\u00e8s API<",
    ">User authentication system (buyers, agents, admins)<": ">Syst\u00e8me d'authentification utilisateur (acheteurs, agents, administrateurs)<",
    ">SEO optimization for property listing pages<": ">Optimisation SEO des pages d'annonces immobili\u00e8res<",
    ">Load testing &amp; performance tuning<": ">Tests de charge &amp; optimisation des performances<",

    # --- Process steps ---
    ">Competitor analysis for study abroad consultancies<": ">Analyse de la concurrence pour les cabinets de conseil en \u00e9tudes \u00e0 l'\u00e9tranger<",
    ">Competitor university website analysis<": ">Analyse de sites web universitaires concurrents<",
    ">Competitor analysis of 5-10 real estate platforms<": ">Analyse de 5 \u00e0 10 plateformes immobili\u00e8res concurrentes<",
    ">Student persona development<": ">D\u00e9veloppement de personas \u00e9tudiants<",
    ">Student persona development by target country<": ">D\u00e9veloppement de personas \u00e9tudiants par pays cible<",
    ">Feature prioritization (MVP vs v2)<": ">Priorisation des fonctionnalit\u00e9s (MVP vs v2)<",
    ">Wireframes for student application workflow<": ">Maquettes fil de fer pour le flux de candidature \u00e9tudiant<",
    ">Wireframes for user &amp; admin flows<": ">Maquettes fil de fer pour les flux utilisateur &amp; admin<",
    ">Student portal wireframes<": ">Maquettes fil de fer du portail \u00e9tudiant<",
    ">High-fidelity UI mockups<": ">Maquettes UI haute fid\u00e9lit\u00e9<",
    ">High-fidelity mockups with country-specific branding<": ">Maquettes haute fid\u00e9lit\u00e9 avec marque sp\u00e9cifique au pays<",
    ">Mobile-responsive mockups<": ">Maquettes responsive mobile<",
    ">Mobile-responsive design for on-the-go students<": ">Design responsive mobile pour les \u00e9tudiants en d\u00e9placement<",
    ">Homepage &amp; key page designs<": ">Designs de la page d'accueil &amp; pages cl\u00e9s<",
    ">Platform design mockups<": ">Maquettes de design de plateforme<",
    ">Property listing page wireframes with search filters<": ">Maquettes fil de fer de pages d'annonces avec filtres de recherche<",
    ">Frontend &amp; backend development with secure auth<": ">D\u00e9veloppement frontend &amp; backend avec authentification s\u00e9curis\u00e9e<",
    ">AI chatbot training on visa requirements and courses<": ">Formation du chatbot IA sur les exigences de visa et les cours<",
    ">CRM integration (HubSpot/Zoho) for lead tracking<": ">Int\u00e9gration CRM (HubSpot/Zoho) pour le suivi des prospects<",
    ">Cross-device testing and QA across browsers<": ">Tests multi-appareils et QA sur tous les navigateurs<",
    ">Counselor training on student portal and CRM<": ">Formation des conseillers sur le portail \u00e9tudiant et le CRM<",
    ">Analytics dashboard setup for tracking conversions<": ">Configuration du tableau de bord analytique pour le suivi des conversions<",
    ">Google Analytics and conversion tracking setup<": ">Configuration de Google Analytics et suivi des conversions<",
    ">QA testing &amp; bug fixes<": ">Tests QA &amp; correction de bugs<",
    ">Final testing &amp; QA<": ">Tests finaux &amp; QA<",
    ">Team training &amp; documentation<": ">Formation de l'\u00e9quipe &amp; documentation<",
    ">Interactive Features &amp; AI Integration<": ">Fonctionnalit\u00e9s Interactives &amp; Int\u00e9gration IA<",
    ">Visa requirement research and documentation<": ">Recherche et documentation des exigences de visa<",
    ">Load testing for simultaneous video consultations<": ">Tests de charge pour les consultations vid\u00e9o simultan\u00e9es<",
    ">HIPAA compliance audit and BAA (Business Associate Agreement)<": ">Audit de conformit\u00e9 HIPAA et BAA (Business Associate Agreement)<",
    ">Provider training on telehealth platform features<": ">Formation des prestataires sur les fonctionnalit\u00e9s de la plateforme de t\u00e9l\u00e9sant\u00e9<",
    ">Insurance reimbursement strategy for telehealth services<": ">Strat\u00e9gie de remboursement d'assurance pour les services de t\u00e9l\u00e9sant\u00e9<",
    ">Telemedicine workflow analysis and use case definition<": ">Analyse du flux de travail de t\u00e9l\u00e9m\u00e9decine et d\u00e9finition des cas d'utilisation<",
    ">HIPAA compliance requirements for video consultations<": ">Exigences de conformit\u00e9 HIPAA pour les consultations vid\u00e9o<",
    ">Custom UI for virtual waiting room and consultation interface<": ">Interface personnalis\u00e9e pour la salle d'attente virtuelle et l'interface de consultation<",
    ">Patient onboarding flow for first-time telehealth users<": ">Flux d'int\u00e9gration patient pour les nouveaux utilisateurs de t\u00e9l\u00e9sant\u00e9<",

    # --- Misc ---
    ">See Pricing<": ">Voir les Tarifs<",
    ">Admission Season Support<": ">Support Saison d'Admission<",
    ">Launch Timeline<": ">Calendrier de Lancement<",
    ">Architecture + DevOps<": ">Architecture + DevOps<",
    ">Complete Student Journey<": ">Parcours \u00c9tudiant Complet<",
    ">Complete User Journey<": ">Parcours Utilisateur Complet<",
    ">Book Free SaaS Demo<": ">R\u00e9server une D\u00e9mo SaaS Gratuite<",
    ">Book Free Study Abroad Demo<": ">R\u00e9server une D\u00e9mo \u00c9tudes \u00e0 l'\u00c9tranger Gratuite<",

    # --- language schools lowercase ---
    ">language schools<": ">\u00e9coles de langues<",
    ">online course platforms<": ">plateformes de cours en ligne<",
}

# Long text translations (these contain HTML entities and are very long)
long_tr = {}

# Process each file
for fname in files:
    fpath = os.path.join(BASE, fname)
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()

    orig_len = len(content)

    # 1. Section translations
    for eng, fr in section_tr.items():
        content = content.replace(eng, fr)

    # 2. Body text translations - sort by length descending
    sorted_body = sorted(body_tr.items(), key=lambda x: len(x[0]), reverse=True)
    for eng, fr in sorted_body:
        if eng != fr:
            content = content.replace(eng, fr)

    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Translated: {fname} ({orig_len} -> {len(content)} chars)")

print("\nDone!")
